baseURL = "https://docs.layer5.io"
title = "Layer5 Documentation"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tags", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]


staticDir = ['static']

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-HX135VWX9B"

# Language configuration

[languages]
[languages.en]
languageName = "English"
# Weight used for sorting.
weight = 1
[languages.en.params]
title = "Layer5"
description = "Product Documentation"


[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "solarized-dark256"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
copyright = "Layer5 Authors"
privacy_policy = "https://layer5.io/company/legal/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.7"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://docs.layer5.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/layer5io/docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/layer5io/docs"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch = "master"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "f475448a7bc1d43a4"
# Layer5 search engine link https://cse.google.com/cse?cx=f475448a7bc1d43a4
# Customization link https://programmablesearchengine.google.com/controlpanel/lookandfeel?cx=f475448a7bc1d43a4

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false

# Sidebar Options
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Enable to show toggle arrows
sidebar_menu_foldable = false
# Limit the number of levels deep the menu displays
# ul_show=1

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/layer5io/docs/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/layer5io/docs/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
	[[params.links.footer.icons]]
		name = "User mailing list"
		url = "https://layer5.io/subscribe"
		icon = "icons/envelope.svg"
		desc = "Discussion and help from your fellow users"
        alt = "Envelope Icon"
	[[params.links.footer.icons]]
		name = "Twitter"
		url = "https://twitter.com/layer5"
		icon = "icons/twitter.svg"
		desc = "Follow us on Twitter to get the latest news!"
		class= "social-icon"
        alt = "Twitter Icon"
	[[params.links.footer.icons]]
		name = "Discussion Forum"
		url = "https://discuss.layer5.io"
		icon = "icons/discuss.svg"
		desc = "Practical questions and curated answers"
        alt = "Discussion Forum Icon"
	[[params.links.footer.icons]]
		name = "GitHub"
		url = "https://github.com/layer5io"
		icon = "icons/github.svg"
		desc = "Development takes place here"
		class= "social-icon"
        alt = "GitHub Icon"
	[[params.links.footer.icons]]
		name = "Slack"
		url = "https://slack.layer5.io"
		icon = "icons/slack.svg"
		desc = "Chat with other project developers"
        alt = "Slack Icon"
	[[params.links.footer.icons]]
		name = "LinkedIn"
		url = "https://www.linkedin.com/company/layer5"
		icon = "icons/linkedin.svg"
		desc = "Discuss development issues around the project"
        alt = "LinkedIn Icon"
	[[params.links.footer.icons]]
		name = "YouTube"
		url = "https://www.youtube.com/channel/UCFL1af7_wdnhHXL1InzaMvA?sub_confirmation=1"
		icon = "icons/youtube.svg"
		desc = "Discuss development issues around the project"
        alt = "YouTube Icon"
	[[params.links.footer.icons]]
		name = "Docker"
		url = "https://hub.docker.com/u/layer5/"
		icon = "icons/docker.svg"
		desc = "Discuss development issues around the project"
        alt = "Docker Icon"

	[[params.links.footer.resources.items]]
		name = "Learning Paths"
		url = "https://layer5.io/learn/learning-paths"
	[[params.links.footer.resources.items]]
		name = "Resource Library"
		url = "https://layer5.io/resources"
	[[params.links.footer.resources.items]]
		name = "Cloud Native Books"
		url = "https://layer5.io/learn/service-mesh-books"
	[[params.links.footer.resources.items]]
		name = "Cloud Native Workshops"
		url = "https://layer5.io/learn/service-mesh-workshops"
	[[params.links.footer.resources.items]]
		name = "Service Mesh Comparison"
		url = "https://layer5.io/service-mesh-landscape#service-mesh-comaprison-matrix"
	[[params.links.footer.resources.items]]
		name = "Cloud Native Interactive Labs"
		url = "https://layer5.io/learn/service-mesh-labs"


	[[params.links.footer.community.items]]
		name = "Blog"
		url = "https://layer5.io/blog"
	[[params.links.footer.community.items]]
		name = "Events"
		url = "https://layer5.io/community/events"
	[[params.links.footer.community.items]]
		name = "Forum"
		url = "https://discuss.layer5.io"
	[[params.links.footer.community.items]]
		name = "FAQ"
		url = "https://layer5.io/company/faq"
	[[params.links.footer.community.items]]
		name = "Programs"
		url = "https://layer5.io/careers/programs"
	[[params.links.footer.community.items]]
		name = "Handbook"
		url = "https://layer5.io/community/handbook"
	[[params.links.footer.community.items]]
		name = "Recognition Program"
		url = "https://badges.layer5.io/"


	[[params.links.footer.projects.items]]
		name = "Kanvas"
		url = "https://layer5.io/cloud-native-management/kanvas"
	[[params.links.footer.projects.items]]
		name = "Meshery"
		url = "https://layer5.io/cloud-native-management/meshery"
	[[params.links.footer.projects.items]]
		name = "Nighthawk"
		url = "https://layer5.io/projects/nighthawk"
	[[params.links.footer.projects.items]]
		name = "Docker Extension"
		url = "https://layer5.io/docker-extension-meshery"
	[[params.links.footer.projects.items]]
		name = "Cloud Native Performance"
		url = "https://layer5.io/projects/cloud-native-performance"


	[[params.links.footer.company.items]]
		name = "News"
		url = "https://layer5.io/company/news"
	[[params.links.footer.company.items]]
		name = "Brands"
		url = "https://layer5.io/company/brand"
	[[params.links.footer.company.items]]
		name = "Pricing"
		url = "https://layer5.io/pricing"
	[[params.links.footer.company.items]]
		name = "Career"
		url = "https://layer5.io/careers"
	[[params.links.footer.company.items]]
		name = "Partners"
		url = "https://layer5.io/partners"
	[[params.links.footer.company.items]]
		name = "Contact"
		url = "https://layer5.io/company/contact"

# hugo module configuration

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
